export const surpriseMePrompts = [
  'a majestic dragon flying over a medieval castle at sunset with its wings spread wide',
  'a futuristic cityscape with flying cars and neon lights illuminating the night sky',
  'a robot chef meticulously preparing a gourmet meal in a high-tech kitchen with advanced appliances',
  'a magical forest filled with glowing mushrooms and fairies fluttering around in the moonlight',
  'a steampunk airship sailing through the clouds with intricate gears and steam engines',
  'a group of penguins having a lively beach party in Hawaii, complete with surfboards and tropical drinks',
  'a cyberpunk detective investigating a crime scene in a dark alley with neon signs flickering',
  'a giant octopus attacking a pirate ship in stormy seas, its tentacles wrapping around the mast',
  'a superhero flying over a bustling metropolis, cape billowing in the wind as they patrol the city',
  'a serene mountain landscape with a crystal-clear lake reflecting the snow-capped peaks',
  'a time traveler exploring ancient Egypt, marveling at the pyramids and hieroglyphics',
  'a whimsical treehouse village nestled in the treetops, connected by rope bridges and ladders',
  'a space explorer discovering a new alien planet with strange flora and fauna',
  'a fantasy castle surrounded by a moat and drawbridge, with banners fluttering in the breeze',
  'a group of adventurers battling a fearsome dragon in a dark and treacherous dungeon',
  'a futuristic robot butler serving drinks at a lavish party, its movements precise and graceful',
  'a mystical unicorn grazing in a meadow filled with colorful flowers and sparkling streams',
  'a pirate treasure map with hidden clues leading to a buried chest of gold and jewels',
  'a haunted mansion on a dark and stormy night, with ghostly apparitions and eerie sounds',
  'a wizard casting a powerful spell in a magical library filled with ancient tomes and artifacts',
  'a mermaid swimming gracefully in an underwater city, surrounded by coral reefs and sea creatures',
  'a knight in shining armor rescuing a princess from a towering castle, sword drawn and ready',
  'a spaceship landing on a distant moon, its crew stepping out to explore the alien landscape',
  'a fairy tale village with cobblestone streets and charming cottages, bustling with activity',
  'a ninja sneaking through a dense bamboo forest, moving silently and swiftly',
  'a carnival with colorful rides and games, the air filled with laughter and music',
  'a detective solving a mystery in a noir city, piecing together clues in the dimly lit streets',
  'a samurai warrior meditating in a tranquil zen garden, surrounded by cherry blossoms',
  'a futuristic sports car racing through a neon-lit city, its engine roaring and lights flashing',
  'a giant robot defending a city from monstrous creatures, its metal fists clashing with their scales',
  'a fantasy landscape with floating islands and cascading waterfalls, bathed in ethereal light',
  'a superhero team assembling for a mission, each member showcasing their unique powers',
  'a dragon hatching from an egg in a dark cave, its scales glistening in the dim light',
  'a magical portal opening to another dimension, swirling with vibrant colors and energy',
  'a group of astronauts exploring a distant galaxy, marveling at the wonders of the universe',
  'a steampunk inventor working on a new creation in a cluttered workshop filled with gadgets',
  'a haunted forest with ghostly apparitions and twisted trees, shrouded in mist',
  'a futuristic city with towering skyscrapers and flying vehicles zipping through the air',
  'a medieval market square bustling with activity, merchants selling their wares and townsfolk chatting',
  'a group of wizards dueling with magical spells, their wands crackling with energy',
  'a pirate ship sailing through a tropical paradise, its crew singing sea shanties',
  'a robot uprising in a dystopian future, machines rebelling against their human creators',
  'a fantasy kingdom with a majestic castle perched on a hill, overlooking the realm',
  'a superhero battling a giant monster in the city, buildings crumbling around them',
  'a time traveler visiting a futuristic metropolis, marveling at the advanced technology',
  'a dragon rider soaring through the skies, the wind rushing past as they navigate the clouds',
  'a magical academy with students learning spells and potions, their wands glowing with power',
  'a space station orbiting a distant planet, its crew conducting experiments in zero gravity',
  'a group of adventurers exploring a hidden temple, uncovering ancient secrets and treasures',
  'a futuristic city park with advanced technology, children playing with robotic companions',
];